### ISSUE TITLE
When I click "Play", nothing happens.

### ISSUE THREAD

**Issue by Ramen-Roxy-AJ** [Sxip/jam#10]
It did something at first, it opened AJ but I accidentally closed Jam and I reopened it, and it does not do anything now. I would appreciate if you told me what may have happened, so I can get a clear understanding of what went wrong. Thank you.

**Comment by Sxip** [comment]
Re-download Animal Jam.

Change `patched` to false in Jam's settings.json. and try again.

**Comment by Ramen-Roxy-AJ** [comment]
So, it opened but it just keeps saying it can't connect to animal jam, when I try again it keeps saying that message.

**Comment by Sxip** [comment]
Sorry for the delay., I have a busy life.

I'm not sure why you're facing this issue. The best advice I can give is to make sure you're doing everything correctly.

**Comment by rayyy-aj** [comment]
When it wouldn't open for me, I kept spamming the play button and now it works.
