### ISSUE TITLE
AJ keeps giving a connection error.

### ISSUE THREAD

**Issue by Xemt** [Sxip/jam#11]
After I log on to AJ (while using Jam), I get the error "Could not connect to Animal Jam. Check your internet connection and try again. [65793]". Also "patched" (in settings.json) is false. I'm using Jam 0.07, and the most recent version of AJ (I believe it's the most recent version). I [first] got this error yesterday (but I didn't check settings.json at that time).

**Comment by Sxip** [comment]
Clear your Animal Jam cache and try again.

**Comment by Xemt** [comment]
Alrighty!

**Comment by Xemt** [comment]
@Sxip It worked, thanks!!
