### ISSUE TITLE
Animal Jam hanging when logging in

### ISSUE THREAD

**Issue by Ramen-Roxy-AJ** [Sxip/jam#3]
Sorry if I ask too many questions, but when I log in and start jam, it freezes, and keeps loading.

**Comment by Sxip** [comment]
I need a little more information. Are you using the latest version? Did you patch the client?

**Comment by Ramen-Roxy-AJ** [comment]
I did patch the client, and I am using the latest version of AJC. It loads when unpatched.

**Comment by Ramen-Roxy-AJ** [comment]
And also my friends have been having this issue too, so I don't think it's just me.

**Comment by Sxip** [comment]
my apologies, I have found the issue you're facing. I will be fixing it now.
