### ISSUE TITLE
patched* it does not go any further then the loading screen

### ISSUE THREAD

**Issue by LYNCAT12** [Sxip/jam#7]
it may be outdated, I tried the newest version and when you try to get past the loading page it only loads 4 dots. It's probably patched and i tried all the older versions none of them work, but the game works fine itself it might just be me but I have tried

**Comment by Ftpv1** [comment]
I'm having the same issue.

**Comment by Sxip** [comment]
I don't actively work on Jam anymore, sorry.

**Comment by LYNCAT12** [comment]
> I'm having the same issue.

hello i have gotten an old jam version to work
